apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      containers:
      - name: app
        image: nginx:1.17
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
        ports:
        - containerPort: 80
        env:
        - name: SECRET_KEY
          value: "hardcoded-secret"
