name: Run Snyk Security Scans

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  snyk-scans:
    uses: ./.github/workflows/snyk-scan.yml
    with:
      project-directory: '.'
      snyk-token: ${{ secrets.SNYK_API_TOKEN }}
